### ISSUE TITLE
nsqd: streaming compression breaks on large messages

### ISSUE THREAD

**Issue by ayamnikov** [nsqio/nsq#1039]
My colleagues and me have noticed some weird behaviour of our services in production. This weird behaviour was caused by timed out PUB operations. After some investigation we figured out that the problem is localized somewhere between our client library (based on pynsq) and a nsqd server. 

After more research we've identified three factors that cause the bug:

- **Enabled compression**. The bug works both for deflate (level=3) and snappy compression. When compression is disabled the bug disappears completely.
- **Large messages**. Message size should exceed some threshold (hundreds or thousands KBs - there is no exact value). For tests I used payloads filled with random bytes. You can't reproduce the bug on small or super-compressible data.
- **Network conditions**. "Better" networks allow to send bigger messages. I tested in two "real" environments (when client and server interacts via ethernet) and on the localhost. The bug appears in each environment.

Trying to localize the problem better I've tested pynsq DeflateSocket implementation - it works good. Also I've learned the server implementation of deflate protocol. My assumption was that the bug is caused by different window size used by compressor and decompressor, but no - both server and client use max window size of 32KB (15 bits). And the bug works for snappy as well, and snappy doesn't have such fine tuning. That's why I believe the root cause of the issue lies somewhere inside server implementation.

I wrote a minimal working example. It uses `nsqd v1.0.0-compat (built w/go1.8)`, `python 2.7`, `pynsq==0.8.2`, `tornado==4.5`, and optionally `python-snappy==0.5.2`. Tested on Ubuntu 17.10.

Run nsqd:

```
./nsqd -max-msg-size 5000000000 -data-path /tmp
```

Here is the example: https://gist.github.com/ayamnikov/26cc73e07d4c9fef5868bbf278596a62

Connection params from nsqd logs: `[nsqd] 2018/06/05 19:40:03.008375 [127.0.0.1:52006] IDENTIFY: {ClientID:andrey Hostname:andrey HeartbeatInterval:30000 OutputBufferSize:16384 OutputBufferTimeout:250 FeatureNegotiation:true TLSv1:false Deflate:false DeflateLevel:3 Snappy:true SampleRate:0 UserAgent:pynsq/0.8.2 MsgTimeout:0}`

When enabling deflate or snappy (via USE_DEFLATE and USE_SNAPPY flags) then timeout happens. When disabling compression then all works perfect.

**Comment by ayamnikov** [comment]
@mreiferson 

Here is the full client output:
```
INFO:nsq.writer:starting writer...
INFO:nsq.writer:[127.0.0.1:4150] connecting to nsqd
INFO:nsq.reader:[8de177ff780246d0a578d5c899b62bb1:be4c79e3a93d44e88e887b8289a15099] starting reader for 8de177ff780246d0a578d5c899b62bb1/be4c79e3a93d44e88e887b8289a15099...
INFO:nsq.reader:[127.0.0.1:4150:8de177ff780246d0a578d5c899b62bb1:be4c79e3a93d44e88e887b8289a15099] connecting to nsqd
INFO:nsq.client:[127.0.0.1:4150:127.0.0.1:4150] IDENTIFY sent {u'tls_v1': False, u'deflate_level': 3, u'deflate': True, u'heartbeat_interval': 30000, u'output_buffer_size': 16384, u'client_id': u'andrey', u'feature_negotiation': True, u'output_buffer_timeout': 250, u'short_id': u'andrey', u'hostname': 'andrey', u'snappy': False, u'sample_rate': 0, u'user_agent': u'pynsq/0.8.2', u'long_id': 'andrey'}
INFO:nsq.client:[127.0.0.1:4150:8de177ff780246d0a578d5c899b62bb1:be4c79e3a93d44e88e887b8289a15099] IDENTIFY sent {u'tls_v1': False, u'deflate_level': 3, u'deflate': True, u'heartbeat_interval': 30000, u'output_buffer_size': 16384, u'client_id': u'andrey', u'feature_negotiation': True, u'output_buffer_timeout': 250, u'short_id': u'andrey', u'hostname': 'andrey', u'snappy': False, u'sample_rate': 0, u'user_agent': u'pynsq/0.8.2', u'long_id': 'andrey'}
INFO:nsq.client:[127.0.0.1:4150:127.0.0.1:4150] IDENTIFY received {u'max_deflate_level': 6, u'deflate_level': 0, u'output_buffer_timeout': 250, u'output_buffer_size': 16384, u'auth_required': False, u'tls_v1': False, u'deflate': True, u'snappy': False, u'version': u'1.0.0-compat', u'msg_timeout': 60000, u'max_rdy_count': 2500, u'sample_rate': 0, u'max_msg_timeout': 900000}
INFO:nsq.client:[127.0.0.1:4150:8de177ff780246d0a578d5c899b62bb1:be4c79e3a93d44e88e887b8289a15099] IDENTIFY received {u'max_deflate_level': 6, u'deflate_level': 0, u'output_buffer_timeout': 250, u'output_buffer_size': 16384, u'auth_required': False, u'tls_v1': False, u'deflate': True, u'snappy': False, u'version': u'1.0.0-compat', u'msg_timeout': 60000, u'max_rdy_count': 2500, u'sample_rate': 0, u'max_msg_timeout': 900000}
Received message: '\xe0\x00\xa1)%\x8d\t}\x92\t{8\xc8)\xablC\xe6\xab\xcb\xfd\xc2\xea,\x02X\x01\xbf\x17?\xeb\x85\xb0a\xb4-H\xe3%\xf8'... (1024 bytes)
Received message: '\xbd\xc74O\xfe\xe8\x17\xc5.6\xc67\xd8;\x80/\xcdJP \xbc\xd5m\xc6\xf4_\xf6\xd6R\xe9T[\x8e\x8f[\xf2\xdd8Hm'... (10240 bytes)
Received message: '\x14\t\xef\x9d?\xcd\x13Y!\x87\xc7\xa3\x83t\xd4\x1e$LD\xe9H\xce"\xb0>\x13PY\xacU,\x91\x04\x98\xbfMW\xf9\x07\xb7'... (61440 bytes)
Received message: '@\x7f\xdf\x0fv\xde8t\xea\xf1a\xdd&62"Y\x9d\xc9\x0b^d\x82\xc8\x9c\xb2\xd4R\x0b\xfa1TL;\x1aq1\x06\xc6\xdd'... (512000 bytes)
Received message: '\xe1V\x8e\x03(\xb25z\x8bf\xa0\x06\xe75\\6g\xbf_\x87\xc7\xb4\xf3\xcc\x1a\x91\xee\xa4\r\x1b\x16A1\x07%\x00f\x14\xf7*'... (1048576 bytes)
Received message: '\x05p\xfe\xda"\x0c\x83b\x1b\x92Cm\xca/\xe6\xae\xfdzfuv\xf2d\x02I\\\x8c\x0f\xf2\x9c\x1dN\x95`z\x0fM\xd1\x9c}'... (2097152 bytes)
Received message: '\xb4\xe9\x17%\x9a\xde\x925\x10\xc3C\xab\x16\x1a\x05\x17U\xd9\x8e\xa8$\xb9\x03\xd7\xdd\xc7s_\x92\xae\xfd\xac*\xec\xf3\xe0\xcc\x8d\x93\xf7'... (5242880 bytes)
Received message: 'Ci\x11@\x0cH\x15@\x07\x02\xff\xba\x86\x8cB?!\x84\xe4T\xff\xb6\xfb9\xb2\x88\x18\x85HQ\x91&\x1e!R\x80z\xec\xdfW'... (10485760 bytes)
Traceback (most recent call last):
  File "/home/andrey/projects/ivideon/misc/nsq_compression_issue/client.py", line 96, in <module>
    ioloop.IOLoop.current().run_sync(main)
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/andrey/projects/ivideon/misc/nsq_compression_issue/client.py", line 91, in main
    msg_rcvd = yield QUEUE.get(timeout=(time.time() + 10))
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
tornado.gen.TimeoutError
```

And full server output:

```
[nsqd] 2018/06/05 20:37:58.094022 nsqd v1.0.0-compat (built w/go1.8)
[nsqd] 2018/06/05 20:37:58.094047 ID: 473
[nsqd] 2018/06/05 20:37:58.094059 NSQ: persisting topic/channel metadata to /tmp/nsqd.dat
[nsqd] 2018/06/05 20:37:58.140860 TCP: listening on [::]:4150
[nsqd] 2018/06/05 20:37:58.141129 HTTP: listening on [::]:4151
[nsqd] 2018/06/05 20:38:03.959683 TCP: new client(127.0.0.1:34958)
[nsqd] 2018/06/05 20:38:03.959811 TCP: new client(127.0.0.1:34960)
[nsqd] 2018/06/05 20:38:03.959961 CLIENT(127.0.0.1:34958): desired protocol magic '  V2'
[nsqd] 2018/06/05 20:38:03.960415 [127.0.0.1:34958] IDENTIFY: {ClientID:andrey Hostname:andrey HeartbeatInterval:30000 OutputBufferSize:16384 OutputBufferTimeout:250 FeatureNegotiation:true TLSv1:false Deflate:true DeflateLevel:3 Snappy:false SampleRate:0 UserAgent:pynsq/0.8.2 MsgTimeout:0}
[nsqd] 2018/06/05 20:38:03.960527 PROTOCOL(V2): [127.0.0.1:34958] upgrading connection to deflate
[nsqd] 2018/06/05 20:38:03.960710 CLIENT(127.0.0.1:34960): desired protocol magic '  V2'
[nsqd] 2018/06/05 20:38:03.960772 [127.0.0.1:34960] IDENTIFY: {ClientID:andrey Hostname:andrey HeartbeatInterval:30000 OutputBufferSize:16384 OutputBufferTimeout:250 FeatureNegotiation:true TLSv1:false Deflate:true DeflateLevel:3 Snappy:false SampleRate:0 UserAgent:pynsq/0.8.2 MsgTimeout:0}
[nsqd] 2018/06/05 20:38:03.960801 PROTOCOL(V2): [127.0.0.1:34960] upgrading connection to deflate
[nsqd] 2018/06/05 20:38:03.961410 TOPIC(8de177ff780246d0a578d5c899b62bb1): created
[nsqd] 2018/06/05 20:38:03.961430 NSQ: persisting topic/channel metadata to /tmp/nsqd.dat
[nsqd] 2018/06/05 20:38:04.026721 TOPIC(8de177ff780246d0a578d5c899b62bb1): new channel(be4c79e3a93d44e88e887b8289a15099)
[nsqd] 2018/06/05 20:38:04.026795 NSQ: persisting topic/channel metadata to /tmp/nsqd.dat
[nsqd] 2018/06/05 20:38:17.837762 PROTOCOL(V2): [127.0.0.1:34960] exiting ioloop
[nsqd] 2018/06/05 20:38:17.837840 ERROR: client(127.0.0.1:34960) - failed to read command - unexpected EOF
[nsqd] 2018/06/05 20:38:17.837777 ERROR: [127.0.0.1:34958] - E_BAD_MESSAGE PUB failed to read message body - unexpected EOF
[nsqd] 2018/06/05 20:38:17.837918 ERROR: [127.0.0.1:34958] - write tcp 127.0.0.1:4150->127.0.0.1:34958: write: broken pipe - unexpected EOF
[nsqd] 2018/06/05 20:38:17.837975 PROTOCOL(V2): [127.0.0.1:34958] exiting ioloop
[nsqd] 2018/06/05 20:38:17.837985 ERROR: client(127.0.0.1:34958) - E_BAD_MESSAGE PUB failed to read message body
[nsqd] 2018/06/05 20:38:17.837990 PROTOCOL(V2): [127.0.0.1:34958] exiting messagePump
[nsqd] 2018/06/05 20:38:17.837925 PROTOCOL(V2): [127.0.0.1:34960] exiting messagePump

```

Also I've updated the gist: https://gist.github.com/ayamnikov/26cc73e07d4c9fef5868bbf278596a62

**Comment by mreiferson** [comment]
I don't see anything surprising in the `nsqd` logs. I'm thinking that this is likely a pynsq issue more than an `nsqd` one. We could possibly confirm this by trying the same test with a go-nsq based client?

**Comment by ayamnikov** [comment]
@mreiferson, I think the simplest way is to use `to_nsq` utility. Something like that:

1. Start nsqd: `./nsqd -max-msg-size 5000000000 -data-path /tmp`
2. Make large file: `dd if=/dev/urandom of=test.msg bs=50M count=1` 
3. Publish: `./to_nsq --topic=$(uuidgen) --nsqd-tcp-address 127.0.0.1:4150 --producer-opt="Deflate=true" --rate 1 < test.msg` (actually it doesn't work at all cuz I don't know how to pass deflate settings to this command :( )

**Comment by SpaTmole** [comment]
Hello, @mreiferson 
I've written this case in go-nsq (https://github.com/SpaTmole/go-nsq-test) but the issue still remains.
Although it has taken bigger messages to reproduce, so I guess it might somehow depend on the time of execution.

Here are the logs:
#### Snappy:
```
nsqd_1   | [nsqd] 2018/06/15 16:24:37.356517 TCP: new client(127.0.0.1:42950)
nsqd_1   | [nsqd] 2018/06/15 16:24:37.356564 CLIENT(127.0.0.1:42950): desired protocol magic '  V2'
nsqd_1   | [nsqd] 2018/06/15 16:24:37.357082 [127.0.0.1:42950] IDENTIFY: {ClientID:d013171269a2 Hostname:d013171269a2 HeartbeatInterval:30000 OutputBufferSize:16384 OutputBufferTimeout:250 FeatureNegotiation:true TLSv1:false Deflate:false DeflateLevel:3 Snappy:true SampleRate:0 UserAgent:go-nsq/1.0.7 MsgTimeout:0}
nsqd_1   | [nsqd] 2018/06/15 16:24:37.357462 PROTOCOL(V2): [127.0.0.1:42950] upgrading connection to snappy
nsqd_1   | [nsqd] 2018/06/15 16:25:28.579264 ERROR: [127.0.0.1:42950] - E_BAD_MESSAGE PUB failed to read message body - snappy: corrupt input
nsqd_1   | [nsqd] 2018/06/15 16:25:28.579413 ERROR: [127.0.0.1:42950] - write tcp 127.0.0.1:4150->127.0.0.1:42950: write: broken pipe - snappy: corrupt input
nsqd_1   | [nsqd] 2018/06/15 16:25:28.579421 PROTOCOL(V2): [127.0.0.1:42950] exiting ioloop
nsqd_1   | [nsqd] 2018/06/15 16:25:28.579449 ERROR: client(127.0.0.1:42950) - E_BAD_MESSAGE PUB failed to read message body
nsqd_1   | [nsqd] 2018/06/15 16:25:28.579477 PROTOCOL(V2): [127.0.0.1:42950] exiting messagePump
nsqd_1   | [nsqd] 2018/06/15 16:25:37.793435 PROTOCOL(V2): [127.0.0.1:42948] exiting ioloop
nsqd_1   | [nsqd] 2018/06/15 16:25:37.793476 ERROR: client(127.0.0.1:42948) - failed to read command - read tcp 127.0.0.1:4150->127.0.0.1:42948: read: connection reset by peer
nsqd_1   | [nsqd] 2018/06/15 16:25:37.793485 PROTOCOL(V2): [127.0.0.1:42948] exiting messagePump

```
> Failed at 1000 MB message.

#### Deflate:
```
nsqd_1   | [nsqd] 2018/06/15 15:41:16.861217 HTTP: listening on [::]:4151
nsqd_1   | [nsqd] 2018/06/15 15:41:16.861237 TCP: listening on [::]:4150
nsqd_1   | [nsqd] 2018/06/15 15:41:17.818977 TCP: new client(127.0.0.1:52722)
nsqd_1   | [nsqd] 2018/06/15 15:41:17.818987 CLIENT(127.0.0.1:52722): desired protocol magic '  V2'
nsqd_1   | [nsqd] 2018/06/15 15:41:17.819087 [127.0.0.1:52722] IDENTIFY: {ClientID:d013171269a2 Hostname:d013171269a2 HeartbeatInterval:30000 OutputBufferSize:16384 OutputBufferTimeout:250 FeatureNegotiation:true TLSv1:false Deflate:true DeflateLevel:3 Snappy:false SampleRate:0 UserAgent:go-nsq/1.0.7 MsgTimeout:0}
nsqd_1   | [nsqd] 2018/06/15 15:41:17.819132 PROTOCOL(V2): [127.0.0.1:52722] upgrading connection to deflate
nsqd_1   | [nsqd] 2018/06/15 15:41:24.540536 ERROR: [127.0.0.1:52722] - E_BAD_MESSAGE PUB failed to read message body - unexpected EOF
nsqd_1   | [nsqd] 2018/06/15 15:41:24.540623 ERROR: [127.0.0.1:52722] - write tcp 127.0.0.1:4150->127.0.0.1:52722: write: broken pipe - unexpected EOF
nsqd_1   | [nsqd] 2018/06/15 15:41:24.540630 PROTOCOL(V2): [127.0.0.1:52722] exiting ioloop
nsqd_1   | [nsqd] 2018/06/15 15:41:24.540658 ERROR: client(127.0.0.1:52722) - E_BAD_MESSAGE PUB failed to read message body
nsqd_1   | [nsqd] 2018/06/15 15:41:24.540666 PROTOCOL(V2): [127.0.0.1:52722] exiting messagePump
nsqd_1   | [nsqd] 2018/06/15 15:41:33.483959 PROTOCOL(V2): [127.0.0.1:52720] exiting ioloop
nsqd_1   | [nsqd] 2018/06/15 15:41:33.484000 ERROR: client(127.0.0.1:52720) - failed to read command - read tcp 127.0.0.1:4150->127.0.0.1:52720: read: connection reset by peer
nsqd_1   | [nsqd] 2018/06/15 15:41:33.484008 PROTOCOL(V2): [127.0.0.1:52720] exiting messagePump
```
> Failed at 90MB message.

Don't hesitate to ask if you'll need any additional info.

Thanks.

**Comment by SpaTmole** [comment]
Hello, @mreiferson 
After a research, I've found that NSQD works fine.
I've created a PR and an issue for pynsq https://github.com/nsqio/pynsq/issues/207
In case of Golang example - I had to configure the `WriteTimeout` within `Config` struct.

So, this issue might be closed.
Thanks.
