### ISSUE TITLE
nsqd: panic on shutdown due to concurrent map iteration and map write

### ISSUE THREAD

**Issue by pteichman** [nsqio/nsq#1327]
We recently saw a panic during shutdown on v1.2.0 and experienced some data loss as a result. Looks like a missing Lock/Unlock around the last channelMap iteration in topic.exit().

`Mar 09 02:44:33 nsqbuffer01 nsqd[12018]: fatal error: concurrent map iteration and map write`

I'll attach the full shutdown log too, but here's the stack trace of the goroutine that crashed:
```
goroutine 1 [running]:
runtime.throw(0x92a39d, 0x26)
        /opt/go/src/runtime/panic.go:1116 +0x72 fp=0xc00e0abc10 sp=0xc00e0abbe0 pc=0x438e72
runtime.mapiternext(0xc00e0abd20)
        /opt/go/src/runtime/map.go:853 +0x554 fp=0xc00e0abc90 sp=0xc00e0abc10 pc=0x412714
github.com/nsqio/nsq/nsqd.(*Topic).exit(0xc0002820c0, 0xc000202200, 0x0, 0x0)
        /go/src/github.com/fastly/nsq/nsqd/topic.go:382 +0x308 fp=0xc00e0abd90 sp=0xc00e0abc90 pc=0x837328
github.com/nsqio/nsq/nsqd.(*Topic).Close(...)
        /go/src/github.com/fastly/nsq/nsqd/topic.go:345
github.com/nsqio/nsq/nsqd.(*NSQD).Exit(0xc000236000)
        /go/src/github.com/fastly/nsq/nsqd/nsqd.go:442 +0x1cb fp=0xc00e0abe50 sp=0xc00e0abd90 pc=0x82246b
main.(*program).Stop.func1()
        /go/src/github.com/fastly/nsq/apps/nsqd/main.go:93 +0x2e fp=0xc00e0abe68 sp=0xc00e0abe50 pc=0x83fece
sync.(*Once).doSlow(0xc000204120, 0xc00034dec8)
        /opt/go/src/sync/once.go:66 +0xec fp=0xc00e0abeb8 sp=0xc00e0abe68 pc=0x4884ac
sync.(*Once).Do(...)
        /opt/go/src/sync/once.go:57
main.(*program).Stop(0xc000204120, 0x0, 0x2)
        /go/src/github.com/fastly/nsq/apps/nsqd/main.go:92 +0x66 fp=0xc00e0abee8 sp=0xc00e0abeb8 pc=0x83e406
github.com/judwhite/go-svc/svc.Run(0x9b19e0, 0xc000204120, 0xc000204140, 0x2, 0x2, 0x0, 0x0)
        /go/pkg/mod/github.com/judwhite/go-svc@v1.0.0/svc/svc_other.go:32 +0x133 fp=0xc00e0abf28 sp=0xc00e0abee8 pc=0x524753
main.main()
        /go/src/github.com/fastly/nsq/apps/nsqd/main.go:28 +0xa5 fp=0xc00e0abf88 sp=0xc00e0abf28 pc=0x83da45
runtime.main()
        /opt/go/src/runtime/proc.go:204 +0x209 fp=0xc00e0abfe0 sp=0xc00e0abf88 pc=0x43b669
runtime.goexit()
        /opt/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00e0abfe8 sp=0xc00e0abfe0 pc=0x471001

```

**Comment by pteichman** [comment]
[panic.txt](https://github.com/nsqio/nsq/files/6152652/panic.txt)

**Comment by mreiferson** [comment]
thanks for the detailed report, fixing this in 539d64ba as part of #1314 since I've already been working on these exit paths there
