### ISSUE TITLE
Error: write EPIPE  at afterWriteDispatched

### ISSUE THREAD

**Issue by anggidast** [nsqio/nsq#1406]
I trying to publish message with nsq writer, but I got this error in several times (about every 30 minutes)
error:

**Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:817:11)
    at Socket._write (node:net:829:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at NSQDConnection.write (/usr/src/app/node_modules/nsqjs/lib/nsqdconnection.js:423:22)
    at Message.<anonymous> (/usr/src/app/node_modules/nsqjs/lib/nsqdconnection.js:397:12)
    at Message.emit (node:events:527:28)**

at the writer I chunk the message so it's not to big at every publish:

**const batchBody = _.chunk<any>(body, 50);
  for (const chunk of batchBody) {
    const bodyMessage = {
      uuid: uuidv4(),
      events: JSON.stringify(chunk)
    };
    Writer.publish(topic, bodyMessage, async err => {
      if (err) {
        console.error("NSQ: Flushing messages failed");
        console.error(err.message);
        return;
      }
      console.log(
        `NSQ: Flushing messages finished`
      );
    });
  }**

at the reader I use:
- 5 maxInFlight
- 10 maxAttempts
- 900000 messageTimeout (default messageTimeout will produce error "failed ID not in flight")
every message chunk in reader will execute asynchronously (http request) with promise.all

is there any suggestion or workaround to solve this problem?
thanks in advance!

**Comment by mreiferson** [comment]
this looks like a client specific issue (some Node client), I would ask this question to the maintainers of that client.

**Comment by anggidast** [comment]
okay, waiting for any updates
