### ISSUE TITLE
nsqd: deadlock NSQD.Exit() on Windows

### ISSUE THREAD

**Issue by xushichangdesmond** [nsqio/nsq#799]
Running on a mac seems ok, but running the below on my Windows 10 machine has me stuck in Exit for a very long time.

One of the stack traces for the goroutines that look a little fishy to me is:

```
goroutine 36 [syscall, locked to thread]:
syscall.Syscall(0x7ffefbc54530, 0x1, 0x2e0, 0x0, 0x0, 0x4a, 0x81, 0x4a)
        E:/Go/src/runtime/syscall_windows.go:163 +0x6b
syscall.FlushFileBuffers(0x2e0, 0xc04220e000, 0x4a)
        E:/Go/src/syscall/zsyscall_windows.go:923 +0x6b
syscall.Fsync(0x2e0, 0x0, 0x4a)
        E:/Go/src/syscall/syscall_windows.go:524 +0x32
os.(*File).Sync(0xc042118088, 0xc04220e000, 0x4a)
        E:/Go/src/os/file_posix.go:121 +0x45
github.com/nsqio/nsq/nsqd.(*NSQD).PersistMetadata(0xc042144000, 0xc0421260c0, 0xc0421e7ed8)
        F:/work/src/github.com/nsqio/nsq/nsqd/nsqd.go:369 +0xe66
github.com/nsqio/nsq/nsqd.(*NSQD).Notify.func1()
        F:/work/src/github.com/nsqio/nsq/nsqd/nsqd.go:551 +0x14e
github.com/nsqio/nsq/internal/util.(*WaitGroupWrapper).Wrap.func1(0xc04219a180, 0xc0421440e0)
        F:/work/src/github.com/nsqio/nsq/internal/util/wait_group_wrapper.go:14 +0x2e
created by github.com/nsqio/nsq/internal/util.(*WaitGroupWrapper).Wrap
        F:/work/src/github.com/nsqio/nsq/internal/util/wait_group_wrapper.go:16 +0x69
```

``` go
package main

import (
    nsq "github.com/nsqio/go-nsq"
    "github.com/nsqio/nsq/nsqd"
)

func main() {
    opts := nsqd.NewOptions()
    nsqd := nsqd.New(opts)
    nsqd.Main()
    p, _ := nsq.NewProducer("127.0.0.1:4150", nsq.NewConfig())
    p.Publish("abc", []byte("hello"))
    nsqd.Exit()
}
```

**Comment by mreiferson** [comment]
I don't have a Windows machine to reproduce, can you help @judwhite?

**Comment by judwhite** [comment]
@xushichangdesmond Can't repro. Are you still having this issue? Is it consistent? How are you running the executable?

/cc @mreiferson

```go
package main

import (
	"log"

	"github.com/nsqio/go-nsq"
	"github.com/nsqio/nsq/nsqd"
)

func main() {
	opts := nsqd.NewOptions()
	nsqd := nsqd.New(opts)
	log.Println("nsqd.Main...")
	nsqd.Main()
	log.Println("nsq.NewProducer...")
	p, err := nsq.NewProducer("127.0.0.1:4150", nsq.NewConfig())
	if err != nil {
		log.Printf("ERR: %v\n", err)
	}
	log.Println("p.Publish...")
	err = p.Publish("abc", []byte("hello"))
	if err != nil {
		log.Printf("ERR: %v\n", err)
	}
	log.Println("nsqd.Exit...")
	nsqd.Exit()
	log.Println("Done.")
}
```

```
[nsqd] 2017/02/19 00:03:36.699711 nsqd v1.0.0-alpha (built w/go1.8)
[nsqd] 2017/02/19 00:03:36.701211 ID: 28
2017/02/19 00:03:36 nsqd.Main...
[nsqd] 2017/02/19 00:03:36.707713 TCP: listening on [::]:4150
2017/02/19 00:03:36 nsq.NewProducer...
[nsqd] 2017/02/19 00:03:36.709713 HTTP: listening on [::]:4151
2017/02/19 00:03:36 p.Publish...
2017/02/19 00:03:36 INF    1 (127.0.0.1:4150) connecting to nsqd
[nsqd] 2017/02/19 00:03:36.722716 TCP: new client(127.0.0.1:64546)
[nsqd] 2017/02/19 00:03:36.725216 CLIENT(127.0.0.1:64546): desired protocol magic '  V2'
[nsqd] 2017/02/19 00:03:36.728717 [127.0.0.1:64546] IDENTIFY: {ClientID:WN7X64-4C66G12 Hostname:WN7X64-4C66G12 HeartbeatInterval:30000 OutputBufferSize:16384 OutputBufferTimeout:250 FeatureNegotiation:true TLSv1:false Deflate:false DeflateLevel:6 Snappy:false SampleRate:0 UserAgent:go-nsq/1.0.6 MsgTimeout:0}
[nsqd] 2017/02/19 00:03:36.732718 TOPIC(abc): created
[nsqd] 2017/02/19 00:03:36.734718 NSQ: persisting topic/channel metadata to nsqd.dat
2017/02/19 00:03:36 nsqd.Exit...
[nsqd] 2017/02/19 00:03:36.742220 HTTP: closing [::]:4151
[nsqd] 2017/02/19 00:03:36.745720 TCP: closing [::]:4150
[nsqd] 2017/02/19 00:03:36.768725 NSQ: persisting topic/channel metadata to nsqd.dat
[nsqd] 2017/02/19 00:03:36.797731 NSQ: closing topics
[nsqd] 2017/02/19 00:03:36.797731 TOPIC(abc): closing
[nsqd] 2017/02/19 00:03:36.798231 TOPIC(abc): closing ... messagePump
[nsqd] 2017/02/19 00:03:36.801732 TOPIC(abc): flushing 1 memory messages to backend
[nsqd] 2017/02/19 00:03:36.809233 DISKQUEUE(abc): writeOne() opened abc.diskqueue.000000.dat
[nsqd] 2017/02/19 00:03:36.810233 DISKQUEUE(abc): closing
[nsqd] 2017/02/19 00:03:36.815234 DISKQUEUE(abc): readOne() opened abc.diskqueue.000000.dat
[nsqd] 2017/02/19 00:03:36.815734 DISKQUEUE(abc): closing ... ioLoop
[nsqd] 2017/02/19 00:03:36.833238 LOOKUP: closing
[nsqd] 2017/02/19 00:03:36.833238 QUEUESCAN: closing
2017/02/19 00:03:36 Done.
```

**Comment by xushichangdesmond** [comment]
it was consistent when i filed this. but I left the job so to say and am no
longer using nsqd at the moment.

it was easily reproducible using the sample code and running with go run.

i suppose this should be closed if nobody else seems to be affected here.

Thanks.

**Comment by judwhite** [comment]
@xushichangdesmond I just tried this with `go run` and it worked on Win7. I'll try on Win10 shortly and see if I can get repro; if not I agree it's probably best to close. Congrats on the new job!

**Comment by mreiferson** [comment]
Closing, re-open if it's reproducible.
