### ISSUE TITLE
nsqadmin panics

### ISSUE THREAD

**Issue by zegl** [nsqio/nsq#860]
`nsqadmin` repeatedly crashes locally on my development machine.

OS: `macOS 10.12.3`
NSQ version: `v0.3.8`

Full output log: https://gist.github.com/zegl/2d96b4597a571c0b4f3e52a6d23ac6f7

Panic log:
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x668b7783f952 pc=0x103c60]

goroutine 18 [running]:
runtime.throw(0x5989c0, 0x2a)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90 fp=0xc82004d5a0 sp=0xc82004d588
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc82004d5f0 sp=0xc82004d5a0
sync.(*Pool).Get(0x79f050, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/sync/pool.go:102 +0x40 fp=0xc82004d640 sp=0xc82004d5f0
fmt.newPrinter(0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:133 +0x27 fp=0xc82004d680 sp=0xc82004d640
fmt.Sprintf(0x55f740, 0x10, 0xc82004d720, 0x1, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:202 +0x2b fp=0xc82004d6d0 sp=0xc82004d680
github.com/nsqio/nsq/internal/http_api.RespondV1(0xa05d28, 0xc820015c20, 0x668b7783c2d7, 0x495520, 0xc820488dc0)
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/src/github.com/nsqio/nsq/internal/http_api/api_response.go:144 +0x1a2 fp=0xc82004d7b0 sp=0xc82004d6d0
github.com/nsqio/nsq/internal/http_api.V1.func1(0xa05d28, 0xc820015c20, 0xc8204022a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/src/github.com/nsqio/nsq/internal/http_api/api_response.go:82 +0x164 fp=0xc82004d840 sp=0xc82004d7b0
github.com/nsqio/nsq/internal/http_api.Decorate.func1(0xa05d28, 0xc820015c20, 0xc8204022a0, 0x0, 0x0, 0x0)
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/src/github.com/nsqio/nsq/internal/http_api/api_response.go:161 +0x5a fp=0xc82004d898 sp=0xc82004d840
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc820010c00, 0xa05d28, 0xc820015c20, 0xc8204022a0)
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/src/github.com/julienschmidt/httprouter/router.go:299 +0x193 fp=0xc82004d9d8 sp=0xc82004d898
github.com/nsqio/nsq/nsqadmin.(*httpServer).ServeHTTP(0xc8200157d0, 0xa05d28, 0xc820015c20, 0xc8204022a0)
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/src/github.com/nsqio/nsq/nsqadmin/http.go:106 +0x58 fp=0xc82004da10 sp=0xc82004d9d8
github.com/nsqio/nsq/internal/http_api.CompressHandler.func1(0xa05d28, 0xc820015c20, 0xc8204022a0)
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/src/github.com/nsqio/nsq/internal/http_api/compress.go:89 +0x488 fp=0xc82004db50 sp=0xc82004da10
net/http.HandlerFunc.ServeHTTP(0xc8200fd360, 0xa05c28, 0xc820100750, 0xc8204022a0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1618 +0x3a fp=0xc82004db70 sp=0xc82004db50
net/http.serverHandler.ServeHTTP(0xc8200d0280, 0xa05c28, 0xc820100750, 0xc8204022a0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:2081 +0x19e fp=0xc82004dbd0 sp=0xc82004db70
net/http.(*conn).serve(0xc8202b4000)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1472 +0xf2e fp=0xc82004df98 sp=0xc82004dbd0
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82004dfa0 sp=0xc82004df98
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:2137 +0x44e

goroutine 1 [chan receive]:
main.main()
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/apps/nsqadmin/main.go:86 +0x86e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/Cellar/go/1.6.2/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.6.2/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [chan receive]:
main.main.func1(0xc82005c300, 0xc82005c2a0)
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/apps/nsqadmin/main.go:68 +0x36
created by main.main
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/apps/nsqadmin/main.go:70 +0x27f

goroutine 7 [select, locked to thread]:
runtime.gopark(0x5d5238, 0xc820024f28, 0x502800, 0x6, 0x18, 0x2)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820024f28, 0x0, 0x18)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820024f28)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/signal1_unix.go:279 +0x32c
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 8 [IO wait]:
net.runtime_pollWait(0xa058d0, 0x72, 0xa00050)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820052450, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820052450, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8200523f0, 0x0, 0xa05ad0, 0xc8202aa360)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc820026038, 0xc820037ce8, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820026038, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc8200d0280, 0xa04950, 0xc820026038, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:2117 +0x129
github.com/nsqio/nsq/internal/http_api.Serve(0xa04950, 0xc820026038, 0xa059b8, 0xc8200fd360, 0x4fc7e0, 0x4, 0xa05990, 0xc82000c690)
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/src/github.com/nsqio/nsq/internal/http_api/http_server.go:29 +0x3d7
github.com/nsqio/nsq/nsqadmin.(*NSQAdmin).Main.func1()
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/src/github.com/nsqio/nsq/nsqadmin/nsqadmin.go:159 +0x10f
github.com/nsqio/nsq/internal/util.(*WaitGroupWrapper).Wrap.func1(0xc8200fd340, 0xc82005c510)
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/src/github.com/nsqio/nsq/internal/util/wait_group_wrapper.go:14 +0x1d
created by github.com/nsqio/nsq/internal/util.(*WaitGroupWrapper).Wrap
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/src/github.com/nsqio/nsq/internal/util/wait_group_wrapper.go:16 +0x5d

goroutine 9 [chan receive]:
github.com/nsqio/nsq/nsqadmin.(*NSQAdmin).handleAdminActions(0xc82005c4e0)
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/src/github.com/nsqio/nsq/nsqadmin/nsqadmin.go:132 +0x81
github.com/nsqio/nsq/nsqadmin.(*NSQAdmin).Main.func2()
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/src/github.com/nsqio/nsq/nsqadmin/nsqadmin.go:161 +0x20
github.com/nsqio/nsq/internal/util.(*WaitGroupWrapper).Wrap.func1(0xc82000fd30, 0xc82005c510)
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/src/github.com/nsqio/nsq/internal/util/wait_group_wrapper.go:14 +0x1d
created by github.com/nsqio/nsq/internal/util.(*WaitGroupWrapper).Wrap
	/private/tmp/nsq-20160620-5825-1l5bidb/nsq-0.3.8/src/github.com/nsqio/nsq/internal/util/wait_group_wrapper.go:16 +0x5d

goroutine 10 [IO wait]:
net.runtime_pollWait(0xa05810, 0x72, 0xc820126000)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200524c0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200524c0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820052460, 0xc820126000, 0x1000, 0x1000, 0x0, 0xa00050, 0xc82000e048)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820026118, 0xc820126000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/net.go:172 +0xe4
net/http.(*connReader).Read(0xc8200fd420, 0xc820126000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:526 +0x196
bufio.(*Reader).fill(0xc82005c5a0)
	/usr/local/Cellar/go/1.6.2/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc82005c5a0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc82005c5a0, 0x0, 0x0, 0x0, 0x4dc500, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc820015da0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc820015da0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/textproto/reader.go:36 +0x40
net/http.readRequest(0xc82005c5a0, 0x400, 0xc8200861c0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/request.go:721 +0xb6
net/http.(*conn).readRequest(0xc8200d0300, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:705 +0x359
net/http.(*conn).serve(0xc8200d0300)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1425 +0x947
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:2137 +0x44e

goroutine 12 [IO wait]:
net.runtime_pollWait(0xa05750, 0x72, 0xc820141000)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820053250, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820053250, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200531f0, 0xc820141000, 0x1000, 0x1000, 0x0, 0xa00050, 0xc82000e048)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820026190, 0xc820141000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/net.go:172 +0xe4
net/http.(*connReader).Read(0xc8202aa340, 0xc820141000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:526 +0x196
bufio.(*Reader).fill(0xc82005c6c0)
	/usr/local/Cellar/go/1.6.2/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc82005c6c0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc82005c6c0, 0x0, 0x0, 0x0, 0x4dc500, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc8200151a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc8200151a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/textproto/reader.go:36 +0x40
net/http.readRequest(0xc82005c6c0, 0x300, 0xc8200862a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/request.go:721 +0xb6
net/http.(*conn).readRequest(0xc8200d0780, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:705 +0x359
net/http.(*conn).serve(0xc8200d0780)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1425 +0x947
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:2137 +0x44e

goroutine 13 [IO wait]:
net.runtime_pollWait(0xa055d0, 0x72, 0xc8202ad000)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200532c0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200532c0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820053260, 0xc8202ad000, 0x1000, 0x1000, 0x0, 0xa00050, 0xc82000e048)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820026198, 0xc8202ad000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/net.go:172 +0xe4
net/http.(*connReader).Read(0xc8202aa380, 0xc8202ad000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:526 +0x196
bufio.(*Reader).fill(0xc82005c720)
	/usr/local/Cellar/go/1.6.2/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc82005c720, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc82005c720, 0x0, 0x0, 0x0, 0x4dc500, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc8200156b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc8200156b0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/textproto/reader.go:36 +0x40
net/http.readRequest(0xc82005c720, 0x500, 0xc820086380, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/request.go:721 +0xb6
net/http.(*conn).readRequest(0xc8200d0800, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:705 +0x359
net/http.(*conn).serve(0xc8200d0800)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1425 +0x947
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:2137 +0x44e
```

**Comment by jehiah** [comment]
Go 1.6.x is incompatible with mac OS 10.12; you will need to build nsq yourself in the mean time (we are actively working towards a new release)

**Comment by zegl** [comment]
Ok, thank you!
