### ISSUE TITLE
nsqd: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by duyue9522** [nsqio/nsq#910]
hi,
  when i use nsqd --statsd-address=... post data to statsd/Graphite  , the problem happend，my environment is :
```
Centos 6.5 64bit
golang version 1.7.4
nsqd version 1.0
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x51e003]

goroutine 38 [running]:
panic(0x7c1aa0, 0xc420010120)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/nsqio/nsq/nsqd.(*NSQD).statsdLoop(0xc42018c000)
        /data/go/src/github.com/nsqio/nsq/nsqd/statsd.go:126 +0x1983
github.com/nsqio/nsq/nsqd.(*NSQD).Main.func6()
        /data/go/src/github.com/nsqio/nsq/nsqd/nsqd.go:264 +0x2a
github.com/nsqio/nsq/internal/util.(*WaitGroupWrapper).Wrap.func1(0xc420161ba0, 0xc42018c0d8)
        /data/go/src/github.com/nsqio/nsq/internal/util/wait_group_wrapper.go:14 +0x27
created by github.com/nsqio/nsq/internal/util.(*WaitGroupWrapper).Wrap
        /data/go/src/github.com/nsqio/nsq/internal/util/wait_group_wrapper.go:16 +0x62
```

**Comment by mreiferson** [comment]
I think this is a real bug, the line is obviously dereferencing a null pointer. But I'm really confused why this hasn't shown up before?

**Comment by ploxiln** [comment]
Hmm it's hard to see how that line could panic:
https://github.com/nsqio/nsq/blob/v0.3.8/nsqd/statsd.go#L126

```
gcPauses := make(Uint64Slice, length)
```

(it's the same in 1.0.0-compat but moved in master)

**Comment by mreiferson** [comment]
I imagine it's this line: https://github.com/nsqio/nsq/blob/master/nsqd/statsd.go#L126

Where on the first run, `lastMemStats` is `nil`.

**Comment by ploxiln** [comment]
so probably not "nsqd version 0.38" you recon ...

**Comment by mreiferson** [comment]
see #911
