### ISSUE TITLE
nsqadmin: error installing node-sass

### ISSUE THREAD

**Issue by liuyuqiang** [nsqio/nsq#915]
```
npm install
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> node-sass@3.13.1 install /usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall /usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-sass
> node scripts/build.js

Building: /root/.nvm/versions/node/v8.0.0/bin/node /usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/root/.nvm/versions/node/v8.0.0/bin/node',
gyp verb cli   '/usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.0.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb download using dist-url https://nodejs.org/dist
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /root/.pyenv/shims/python2
gyp verb check python version `/root/.pyenv/shims/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.3\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.0.0
gyp verb command install [ '8.0.0' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb download using dist-url https://nodejs.org/dist
gyp verb install input version string "8.0.0"
gyp verb install installing version: 8.0.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.0.0
gyp verb build dir attempting to create "build" dir: /usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /root/.pyenv/shims/python2
gyp info spawn args [ '/usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/8.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb download using dist-url https://nodejs.org/dist
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /root/.node-gyp/8.0.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.3.6"' -I/root/.node-gyp/8.0.0/include/node -I/root/.node-gyp/8.0.0/src -I/root/.node-gyp/8.0.0/deps/uv/include -I/root/.node-gyp/8.0.0/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
In file included from ../src/libsass/src/ast.cpp:2:
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Vectorized<T>::hash()’:
../src/libsass/src/ast.hpp:257: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:260: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:260: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:260: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:260: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:260: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:260: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In constructor ‘Sass::Hashed::Hashed(size_t)’:
../src/libsass/src/ast.hpp:307: error: ‘class Sass::Hashed::ExpressionMap’ has no member named ‘reserve’
../src/libsass/src/ast.hpp: In member function ‘Sass::Hashed& Sass::Hashed::operator+=(Sass::Hashed*)’:
../src/libsass/src/ast.hpp:336: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:340: error: could not convert ‘Sass::Hashed::reset_duplicate_key()’ to ‘bool’
../src/libsass/src/ast.hpp:341: error: expected primary-expression before ‘return’
../src/libsass/src/ast.hpp:341: error: expected ‘)’ before ‘return’
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Map::hash()’:
../src/libsass/src/ast.hpp:936: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:940: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:940: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:940: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:940: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:940: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:940: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Function_Call::hash()’:
../src/libsass/src/ast.hpp:1232: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1234: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1234: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:1234: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1234: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:1234: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1234: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Number::hash()’:
../src/libsass/src/ast.hpp:1361: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1363: error: expected primary-expression before ‘for’
../src/libsass/src/ast.hpp:1363: error: expected ‘;’ before ‘for’
../src/libsass/src/ast.hpp:1363: error: expected primary-expression before ‘for’
../src/libsass/src/ast.hpp:1363: error: expected ‘)’ before ‘for’
../src/libsass/src/ast.hpp:1363: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1365: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1365: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:1365: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1365: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:1365: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1365: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp: In member function ‘bool Sass::String_Schema::has_interpolants()’:
../src/libsass/src/ast.hpp:1502: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1505: error: expected primary-expression before ‘return’
../src/libsass/src/ast.hpp:1505: error: expected ‘;’ before ‘return’
../src/libsass/src/ast.hpp:1505: error: expected primary-expression before ‘return’
../src/libsass/src/ast.hpp:1505: error: expected ‘)’ before ‘return’
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::String_Schema::hash()’:
../src/libsass/src/ast.hpp:1514: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:1516: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1516: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:1516: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1516: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:1516: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:1516: error: expected ‘;’ before ‘}’ token
In file included from ../src/libsass/src/ast.cpp:2:
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Compound_Selector::hash()’:
../src/libsass/src/ast.hpp:2261: error: ‘template<class T> class Sass::Vectorized’ used without template parameters
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Selector_List::hash()’:
../src/libsass/src/ast.hpp:2488: error: ‘template<class T> class Sass::Vectorized’ used without template parameters
../src/libsass/src/ast.hpp: In member function ‘virtual void Sass::Selector_List::set_media_block(Sass::Media_Block*)’:
../src/libsass/src/ast.hpp:2505: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:2508: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:2508: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.hpp:2508: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:2508: error: expected ‘)’ before ‘}’ token
../src/libsass/src/ast.hpp:2508: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:2508: error: expected ‘;’ before ‘}’ token
../src/libsass/src/ast.cpp: In function ‘std::string& Sass::str_ltrim(std::string&)’:
../src/libsass/src/ast.cpp:33: error: expected primary-expression before ‘[’ token
../src/libsass/src/ast.cpp:33: error: expected primary-expression before ‘]’ token
../src/libsass/src/ast.cpp:33: error: expected primary-expression before ‘char’
../src/libsass/src/ast.cpp:33: error: unable to deduce ‘auto’ from ‘<expression error>’
../src/libsass/src/ast.cpp: In function ‘std::string& Sass::str_rtrim(std::string&)’:
../src/libsass/src/ast.cpp:40: error: expected primary-expression before ‘[’ token
../src/libsass/src/ast.cpp:40: error: expected primary-expression before ‘]’ token
../src/libsass/src/ast.cpp:40: error: expected primary-expression before ‘char’
../src/libsass/src/ast.cpp:40: error: unable to deduce ‘auto’ from ‘<expression error>’
../src/libsass/src/ast.cpp: In member function ‘virtual bool Sass::Compound_Selector::has_parent_ref()’:
../src/libsass/src/ast.cpp:139: error: expected initializer before ‘:’ token
../src/libsass/src/ast.cpp:142: error: expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:142: error: expected ‘;’ before ‘return’
../src/libsass/src/ast.cpp:142: error: expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:142: error: expected ‘)’ before ‘return’
../src/libsass/src/ast.cpp: In member function ‘virtual bool Sass::Compound_Selector::is_superselector_of(Sass::Selector_List*, std::string)’:
../src/libsass/src/ast.cpp:661: error: expected initializer before ‘:’ token
../src/libsass/src/ast.cpp:664: error: expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:664: error: expected ‘;’ before ‘return’
../src/libsass/src/ast.cpp:664: error: expected primary-expression before ‘return’
../src/libsass/src/ast.cpp:664: error: expected ‘)’ before ‘return’
../src/libsass/src/ast.cpp: In member function ‘Sass::Selector_List* Sass::Complex_Selector::parentize(Sass::Selector_List*, Sass::Context&)’:
../src/libsass/src/ast.cpp:1171: error: expected initializer before ‘:’ token
../src/libsass/src/ast.cpp:2216: error: expected primary-expression at end of input
../src/libsass/src/ast.cpp:2216: error: expected ‘;’ at end of input
../src/libsass/src/ast.cpp:2216: error: expected primary-expression at end of input
../src/libsass/src/ast.cpp:2216: error: expected ‘)’ at end of input
../src/libsass/src/ast.cpp:2216: error: expected statement at end of input
../src/libsass/src/ast.cpp:2216: error: expected ‘}’ at end of input
../src/libsass/src/ast.cpp:2216: error: expected ‘}’ at end of input
../src/libsass/src/ast.cpp: At global scope:
../src/libsass/src/ast.cpp:2216: error: expected ‘}’ at end of input
../src/libsass/src/units.hpp:10: warning: ‘Sass::PI’ defined but not used
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
make: Leaving directory `/usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 2.6.32-358.el6.x86_64
gyp ERR! command "/root/.nvm/versions/node/v8.0.0/bin/node" "/usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/golang/nsq/src/github.com/nsqio/nsq/nsqadmin/node_modules/node-sass
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN nsqadmin@0.3.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-22T06_45_14_902Z-debug.log
```

**Comment by ploxiln** [comment]
Please use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) for terminal output to make it more readable.

The problem seems to be that the version of node-sass, which is required by the version of gulp-sass, which is specified in nsqadmin's package.json, is too old for your version of nodejs. The ABI numbers of pre-built artifacts on github only go up to "51" for that release, not up to "57". (These appear to correspond to V8 major versions, which seem to track Chromium major versions.)

So the task to be done for this is to update various dependency versions in `package.json`, and check that the compiled web assets output is not significantly changed and/or still works for all practically testable cases.

Just by the way, if you were not trying to change the web frontend assets for nsqadmin, you don't need to npm install, just normal go build process.

**Comment by liuyuqiang** [comment]
node-sass 3.13.1 works with node 7 but not with node 8.  nsqadmin only run node 7 .
